/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/registry/src/lib/utils.ts",
      type: "registry:lib",
    }],
  },
  "use-controllable-state": {
    name: "use-controllable-state",
    description: "",
    type: "registry:hook",
    files: [{
      path: "src/registry/src/hooks/use-layout-effect.tsx",
      type: "registry:hook",
    },{
      path: "src/registry/src/hooks/use-controllable-state.ts",
      type: "registry:hook",
    }],
  },
  "use-sound": {
    name: "use-sound",
    description: "Custom React hook to load and play a sound from a given URL using the Web Audio API.",
    type: "registry:hook",
    files: [{
      path: "src/registry/src/hooks/use-sound.ts",
      type: "registry:hook",
    }],
  },
  "confusion-matrix": {
    name: "confusion-matrix",
    description: "Interactive confusion matrix to visualize classifier performance.",
    type: "registry:component",
    files: [{
      path: "src/registry/src/registry/ds-components/confusion-matrix.tsx",
      type: "registry:component",
    }],
  },
  "model-metrics": {
    name: "model-metrics",
    description: "Visual dashboard for key machine learning performance metrics.",
    type: "registry:component",
    files: [{
      path: "src/registry/src/registry/ds-components/model-metrics.tsx",
      type: "registry:component",
    }],
  },
  "training-progress": {
    name: "training-progress",
    description: "Line chart visualization of model training loss and accuracy over epochs.",
    type: "registry:component",
    files: [{
      path: "src/registry/src/registry/ds-components/training-progress.tsx",
      type: "registry:component",
    }],
  },
  "roc-curve": {
    name: "roc-curve",
    description: "Receiver Operating Characteristic (ROC) curve with Area Under Curve (AUC) metric.",
    type: "registry:component",
    files: [{
      path: "src/registry/src/registry/ds-components/roc-curve.tsx",
      type: "registry:component",
    }],
  },
  "feature-importance": {
    name: "feature-importance",
    description: "Horizontal bar chart showing the relative importance of model features.",
    type: "registry:component",
    files: [{
      path: "src/registry/src/registry/ds-components/feature-importance.tsx",
      type: "registry:component",
    }],
  },
  "data-distribution": {
    name: "data-distribution",
    description: "Histogram visualization showing the frequency distribution of data points.",
    type: "registry:component",
    files: [{
      path: "src/registry/src/registry/ds-components/data-distribution.tsx",
      type: "registry:component",
    }],
  },
  "correlation-heatmap": {
    name: "correlation-heatmap",
    description: "Grid-based heat map visualizing correlation coefficients between features.",
    type: "registry:component",
    files: [{
      path: "src/registry/src/registry/ds-components/correlation-heatmap.tsx",
      type: "registry:component",
    }],
  },
  "wheel-picker-block-01": {
    name: "wheel-picker-block-01",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/wheel-picker-demo.tsx",
      type: "registry:component",
    }],
  },
  "wheel-picker-block-02": {
    name: "wheel-picker-block-02",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/wheel-picker-form-demo.tsx",
      type: "registry:component",
    }],
  },
  "work-experience-block-01": {
    name: "work-experience-block-01",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/work-experience-demo.tsx",
      type: "registry:component",
    }],
  },
  "shimmering-text-block-01": {
    name: "shimmering-text-block-01",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/shimmering-text-demo-01.tsx",
      type: "registry:component",
    }],
  },
  "shimmering-text-block-02": {
    name: "shimmering-text-block-02",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/shimmering-text-demo-02.tsx",
      type: "registry:component",
    }],
  },
  "slide-to-unlock-block-01": {
    name: "slide-to-unlock-block-01",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo-01.tsx",
      type: "registry:component",
    }],
  },
  "slide-to-unlock-block-02": {
    name: "slide-to-unlock-block-02",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo-02.tsx",
      type: "registry:component",
    }],
  },
  "slide-to-unlock-block-03": {
    name: "slide-to-unlock-block-03",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo-03.tsx",
      type: "registry:component",
    }],
  },
  "testimonials-marquee-block-01": {
    name: "testimonials-marquee-block-01",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/testimonials-marquee-demo-01.tsx",
      type: "registry:component",
    }],
  },
  "testimonials-marquee-block-02": {
    name: "testimonials-marquee-block-02",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/testimonials-marquee-demo-02.tsx",
      type: "registry:component",
    }],
  },
  "scroll-fade-effect-block-01": {
    name: "scroll-fade-effect-block-01",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-01.tsx",
      type: "registry:component",
    }],
  },
  "scroll-fade-effect-block-02": {
    name: "scroll-fade-effect-block-02",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-02.tsx",
      type: "registry:component",
    }],
  },
  "scroll-fade-effect-block-03": {
    name: "scroll-fade-effect-block-03",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-03.tsx",
      type: "registry:component",
    }],
  },
  "scroll-fade-effect-block-04": {
    name: "scroll-fade-effect-block-04",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-04.tsx",
      type: "registry:component",
    }],
  },
  "apple-hello-effect-vi-demo": {
    name: "apple-hello-effect-vi-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-vi-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/apple-hello-effect-vi-demo.tsx")),
  },
  "apple-hello-effect-en-demo": {
    name: "apple-hello-effect-en-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-en-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/apple-hello-effect-en-demo.tsx")),
  },
  "theme-switcher-demo": {
    name: "theme-switcher-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/theme-switcher-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/theme-switcher-demo.tsx")),
  },
  "wheel-picker-demo": {
    name: "wheel-picker-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/wheel-picker-demo.tsx")),
  },
  "wheel-picker-form-demo": {
    name: "wheel-picker-form-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-form-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/wheel-picker-form-demo.tsx")),
  },
  "work-experience-demo": {
    name: "work-experience-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/work-experience-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/work-experience-demo.tsx")),
  },
  "shimmering-text-demo-01": {
    name: "shimmering-text-demo-01",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/shimmering-text-demo-01.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/shimmering-text-demo-01.tsx")),
  },
  "shimmering-text-demo-02": {
    name: "shimmering-text-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/shimmering-text-demo-02.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/shimmering-text-demo-02.tsx")),
  },
  "slide-to-unlock-demo-01": {
    name: "slide-to-unlock-demo-01",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo-01.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/slide-to-unlock-demo-01.tsx")),
  },
  "slide-to-unlock-demo-02": {
    name: "slide-to-unlock-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo-02.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/slide-to-unlock-demo-02.tsx")),
  },
  "slide-to-unlock-demo-03": {
    name: "slide-to-unlock-demo-03",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo-03.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/slide-to-unlock-demo-03.tsx")),
  },
  "testimonials-marquee-demo-01": {
    name: "testimonials-marquee-demo-01",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonials-marquee-demo-01.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/testimonials-marquee-demo-01.tsx")),
  },
  "testimonials-marquee-demo-02": {
    name: "testimonials-marquee-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonials-marquee-demo-02.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/testimonials-marquee-demo-02.tsx")),
  },
  "github-stars-demo": {
    name: "github-stars-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-stars-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/github-stars-demo.tsx")),
  },
  "scroll-fade-effect-demo-01": {
    name: "scroll-fade-effect-demo-01",
    description: "A scroll fade effect demo with a list of tags.",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-01.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/scroll-fade-effect-demo-01.tsx")),
  },
  "scroll-fade-effect-demo-02": {
    name: "scroll-fade-effect-demo-02",
    description: "A scroll fade effect demo with horizontal scrolling.",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-02.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/scroll-fade-effect-demo-02.tsx")),
  },
  "scroll-fade-effect-demo-03": {
    name: "scroll-fade-effect-demo-03",
    description: "A scroll fade effect demo using shadcn/ui Scroll Area.",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-03.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/scroll-fade-effect-demo-03.tsx")),
  },
  "scroll-fade-effect-demo-04": {
    name: "scroll-fade-effect-demo-04",
    description: "A demo of ScrollFadeEffect with shadcn/ui Scroll Area (horizontal scrolling).",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-04.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/scroll-fade-effect-demo-04.tsx")),
  },
}